export type LucideIconName =
  | "baggage-claim"
  | "building-2"
  | "calendar"
  | "check-square"
  | "copy"
  | "heart-handshake"
  | "mail-question"
  | "palette"
  | "pen-square"
  | "pie-chart"
  | "pin-off"
  | "pin"
  | "puzzle"
  | "save"
  | "slack"
  | "trash-2"
  | "wallet";
