export const customStyleProps = {
  color: {
    property: "color",
    scale: "colors",
  },
  backgroundColor: {
    property: "backgroundColor",
    scale: "colors",
  },
  borderColor: {
    property: "borderColor",
    scale: "colors",
  },
  borderBottomColor: {
    property: "borderBottomColor",
    scale: "colors",
  },
  borderLeftColor: {
    property: "borderLeftColor",
    scale: "colors",
  },
  borderRightColor: {
    property: "borderRightColor",
    scale: "colors",
  },
  borderTopColor: {
    property: "borderTopColor",
    scale: "colors",
  },
  content: true,
  cursor: true,
  appearance: true,
  transition: true,
  transform: true,
  animation: true,
  transformOrigin: true,
  visibility: true,
  userSelect: true,
  pointerEvents: true,
  boxSizing: true,
  resize: true,
  listStyleType: true,
  listStylePosition: true,
  listStyleImage: true,
  objectFit: true,
  objectPosition: true,
  outline: true,
  float: true,
  willChange: true,
  clip: true,
  backgroundAttachment: true,
  textAlign: true,
  textTransform: true,
  textDecoration: true,
  textOverflow: true,
  whiteSpace: true,
  wordBreak: true,
  wordWrap: true,
  overflowWrap: true,
  opacity: true,
  borderCollapse: true,
  borderSpacing: true,
  tableLayout: true,
  fontVariantNumeric: true,
  inset: true,
  columnGap: {
    property: "columnGap",
    scale: "space",
  },
  rowGap: {
    property: "rowGap",
    scale: "space",
  },
};
