import {
  AlertTriangle,
  BaggageClaim,
  Building2,
  Calendar,
  CheckSquare,
  CheckCircle2,
  ClipboardCheck,
  Copy,
  FilePlus2,
  HeartHandshake,
  Hourglass,
  Info,
  LucideIcon,
  Luggage,
  MailQuestion,
  PauseOctagon,
  Palette,
  Palmtree,
  PenSquare,
  PieChart,
  Pin,
  PinOff,
  Puzzle,
  Save,
  Slack,
  ThumbsUp,
  Trash2,
  UserPlus,
  Wallet,
  FileBarChart,
  Lightbulb,
  Settings2,
  Users,
} from "lucide-react";
import { LucideIconName } from "./types/LucideIconName";

export const LucideIcons: Record<LucideIconName, LucideIcon> = {
  "baggage-claim": BaggageClaim,
  "building-2": Building2,
  calendar: Calendar,
  "check-square": CheckSquare,
  "circle-check": CheckCircle2,
  "clipboard-check": ClipboardCheck,
  copy: Copy,
  "file-plus-2": FilePlus2,
  "file-bar-chart": FileBarChart,
  "heart-handshake": HeartHandshake,
  hourglass: Hourglass,
  info: Info,
  lightbulb: Lightbulb,
  luggage: Luggage,
  "mail-question": MailQuestion,
  "octagon-pause": PauseOctagon,
  palette: Palette,
  palmtree: Palmtree,
  "pen-square": PenSquare,
  "pie-chart": PieChart,
  "pin-off": PinOff,
  pin: Pin,
  puzzle: Puzzle,
  save: Save,
  "settings-2": Settings2,
  slack: Slack,
  "thumbs-up": ThumbsUp,
  "trash-2": Trash2,
  "triangle-alert": AlertTriangle,
  "user-plus": UserPlus,
  wallet: Wallet,
  users: Users,
};
