import {
  AlertTriangle,
  ArrowDown,
  ArrowDownToLine,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpFromLine,
  BadgeEuro,
  BaggageClaim,
  Ban,
  Banknote,
  BookOpen,
  BriefcaseBusiness,
  Building,
  Building2,
  Calendar,
  Camera,
  Check,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  CircleAlert,
  CircleEllipsis,
  CircleHelp,
  CirclePlus,
  CircleUser,
  CircleX,
  ClipboardCheck,
  Clock,
  CloudDownload,
  CloudUpload,
  Cog,
  Copy,
  CreditCard,
  Earth,
  Eye,
  FileBarChart,
  FilePlus2,
  Flag,
  HeartHandshake,
  Home,
  Hourglass,
  Info,
  Lightbulb,
  Link,
  ListPlus,
  LogOut,
  LucideIcon,
  Luggage,
  Mail,
  MailPlus,
  MailQuestion,
  MapPin,
  Menu,
  MessagesSquare,
  Minus,
  MoveLeft,
  Palette,
  Palmtree,
  Paperclip,
  PauseOctagon,
  PenSquare,
  Pencil,
  PieChart,
  Pin,
  PinOff,
  Plus,
  Puzzle,
  Rocket,
  Save,
  Search,
  Settings2,
  ShieldAlert,
  Slack,
  SlidersVertical,
  SquareArrowOutUpRight,
  SquarePen,
  Star,
  ThumbsUp,
  Trash2,
  User,
  UserPlus,
  Users,
  Variable,
  Wallet,
  X,
} from "lucide-react";
import { LucideIconName } from "./types/LucideIconName";

export const LucideIcons: Record<LucideIconName, LucideIcon> = {
  "arrow-down-to-line": ArrowDownToLine,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up-from-line": ArrowUpFromLine,
  "arrow-up": ArrowUp,
  "badge-euro": BadgeEuro,
  "baggage-claim": BaggageClaim,
  ban: Ban,
  banknote: Banknote,
  "book-open": BookOpen,
  "briefcase-business": BriefcaseBusiness,
  "building-2": Building2,
  building: Building,
  calendar: Calendar,
  camera: Camera,
  "check-square": CheckSquare,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "chevrons-left": ChevronsLeft,
  "chevrons-right": ChevronsRight,
  "circle-alert": CircleAlert,
  "circle-check": CheckCircle2,
  "circle-ellipsis": CircleEllipsis,
  "circle-help": CircleHelp,
  "circle-plus": CirclePlus,
  "circle-user": CircleUser,
  "circle-x": CircleX,
  "clipboard-check": ClipboardCheck,
  clock: Clock,
  "cloud-download": CloudDownload,
  "cloud-upload": CloudUpload,
  cog: Cog,
  copy: Copy,
  "credit-card": CreditCard,
  earth: Earth,
  eye: Eye,
  "file-plus-2": FilePlus2,
  "file-bar-chart": FileBarChart,
  flag: Flag,
  "heart-handshake": HeartHandshake,
  home: Home,
  hourglass: Hourglass,
  info: Info,
  lightbulb: Lightbulb,
  link: Link,
  "list-plus": ListPlus,
  "log-out": LogOut,
  luggage: Luggage,
  "mail-question": MailQuestion,
  mail: Mail,
  "map-pin": MapPin,
  menu: Menu,
  "messages-square": MessagesSquare,
  minus: Minus,
  "move-left": MoveLeft,
  "mail-plus": MailPlus,
  "octagon-pause": PauseOctagon,
  palette: Palette,
  palmtree: Palmtree,
  paperclip: Paperclip,
  "pen-square": PenSquare,
  pencil: Pencil,
  "pie-chart": PieChart,
  "pin-off": PinOff,
  pin: Pin,
  plus: Plus,
  puzzle: Puzzle,
  rocket: Rocket,
  save: Save,
  search: Search,
  "settings-2": Settings2,
  "shield-alert": ShieldAlert,
  slack: Slack,
  "sliders-vertical": SlidersVertical,
  "square-arrow-out-up-right": SquareArrowOutUpRight,
  "square-pen": SquarePen,
  star: Star,
  "thumbs-up": ThumbsUp,
  "trash-2": Trash2,
  "triangle-alert": AlertTriangle,
  "user-plus": UserPlus,
  user: User,
  users: Users,
  variable: Variable,
  wallet: Wallet,
  x: X,
};
