import {
  AlertTriangle,
  BaggageClaim,
  Building2,
  Calendar,
  CheckSquare,
  Copy,
  HeartHandshake,
  Info,
  LucideIcon,
  Luggage,
  MailQuestion,
  PauseOctagon,
  Palette,
  Palmtree,
  PenSquare,
  PieChart,
  Pin,
  PinOff,
  Puzzle,
  Save,
  Slack,
  Trash2,
  Wallet,
} from "lucide-react";
import { LucideIconName } from "./types/LucideIconName";

export const LucideIcons: Record<LucideIconName, LucideIcon> = {
  "baggage-claim": BaggageClaim,
  "building-2": Building2,
  calendar: Calendar,
  "check-square": CheckSquare,
  copy: Copy,
  "heart-handshake": HeartHandshake,
  info: Info,
  luggage: Luggage,
  "mail-question": MailQuestion,
  "octagon-pause": PauseOctagon,
  palette: Palette,
  palmtree: Palmtree,
  "pen-square": PenSquare,
  "pie-chart": PieChart,
  "pin-off": PinOff,
  pin: Pin,
  puzzle: Puzzle,
  save: Save,
  slack: Slack,
  "trash-2": Trash2,
  "triangle-alert": AlertTriangle,
  wallet: Wallet,
};
