name: "Assign Reviewers"
on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: "Auto Request Code Review"
        uses: necojackarc/auto-request-review@v0.7.0 # cspell:disable-line
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: .github/reviewers.yml
