name: Package size

on: pull_request

jobs:
  package-size:
    name: Check package sizes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 20.3
        uses: actions/setup-node@v2
        with:
          node-version: 20.3.x

      - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          build-script: "build"
          # only do common js files, no need to double count files
          pattern: "{**/dist/**/*.js, ./packages/**/dist/*.js}"
          exclude: "{**/*.map,**/node_modules/**,**/*.mjs}"
