name: Release

on:
  push:
    paths:
      - "packages/**"
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: yarn

      - name: Setup CI Git User
        run: |
          git config --global user.email "alpacatron@localyzeapp.com"
          git config --global user.name "alpacatron"

      - name: "Creates Pull Request or Publish to npm"
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn release
          commit: "chore(release): version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_BOT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Notify success to Slack
        if: steps.changesets.outputs.published == 'true'
        uses: slackapi/slack-github-action@v1.22.0
        with:
          payload: |
            {
              "message": "✅ Successfully published Pluto to NPM. Published packages:",
              "publishedPackages": ${{ toJson(steps.changesets.outputs.publishedPackages) }}
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify failure to Slack
        if: failure() && steps.changesets.outcome == 'failure'
        uses: slackapi/slack-github-action@v1.22.0
        with:
          payload: |
            {
              "message": "❌ Something went wrong publishing Pluto to NPM",
              "publishedPackages": "No packages were published"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
